# Generated by Django 5.2.9 on 2025-12-05 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GovDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('VOTER', 'Voter ID')], max_length=20)),
                ('doc_number', models.CharField(max_length=64, unique=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('VOTER', 'Voter ID')], max_length=20)),
                ('id_value', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.customer')),
            ],
        ),
        migrations.CreateModel(
            name='KYCSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('SELECT_DOC', 'Select Document'), ('SCAN_DOC', 'Scan Document'), ('UPLOAD_DOC', 'Upload Document'), ('SELFIE', 'Selfie Capture'), ('VERIFY', 'Verify'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SELECT_DOC', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress_percent', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_sessions', to='kyc.customer')),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('VOTER', 'Voter ID')], max_length=20)),
                ('file', models.FileField(upload_to='kyc_docs/')),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.customer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsession')),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('passport_valid', models.BooleanField(blank=True, null=True)),
                ('vendor_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='kyc.kycdocument')),
            ],
        ),
        migrations.CreateModel(
            name='KYCAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('SELECT_DOC', 'Select Document'), ('SCAN_DOC', 'Scan Document'), ('UPLOAD_DOC', 'Upload Document'), ('SELFIE', 'Selfie Capture'), ('VERIFY', 'Verify')], max_length=30)),
                ('attempt_number', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='kyc.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', 'stage'], name='kyc_kycatte_custome_a41cef_idx')],
            },
        ),
    ]
