# Generated by Django 5.2.9 on 2025-12-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsession',
            name='live_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_live_selfies/'),
        ),
        migrations.AddField(
            model_name='kycsession',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
    ]
