# Generated by Django 5.2.9 on 2025-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycsession_live_selfie_kycsession_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsession',
            name='live_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
    ]
