# Generated by Django 5.2.9 on 2025-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kycsession_live_selfie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycindex',
            old_name='id_type',
            new_name='doc_type',
        ),
        migrations.RemoveField(
            model_name='kycindex',
            name='id_value',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='id_number',
            field=models.CharField(default='UNKNOWN', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycindex',
            name='id_hash',
            field=models.CharField(default='EMPTY', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('session', 'doc_type')},
        ),
    ]
